// <auto-generated>
// Generated by tools/generate-folding.py from the Unicode database. Do not edit.
// </auto-generated>

#nullable enable

namespace Fermata.Text;

internal static class FoldingTable
{
    /// <summary>Lowercase, unaccented form of U+00C0..U+024F. NUL marks a letter listed in <see cref="Expansion"/>.</summary>
    public const char LatinFirst = '\u00c0', LatinLast = '\u024f';
    public const string Latin =
        "aaaaaa\0ceeeeiiiidnooooo\u00d7ouuuuy\0\0aaaaaa\0ceeeeiiiidnooooo\u00f7ouuuuy\0yaaaaaaccccccccddd"
        + "deeeeeeeeeegggggggghhhhiiiiiiiiii\0\0jjkkkllllll\u0140\u0140llnnnnnn\u0149nnoooooo\0\0rrrrrrssss"
        + "ssssttttttuuuuuuuuuuuuwwyyyzzzzzzsb\u0253\u0183\u0183\u0185\u0185\u0254\u0188\u0188\u0256\u0257"
        + "\u018c\u018c\u018d\u01dd\u0259\u025bff\u0260\u0263\u0195\u0269i\u0199\u0199\u019a\u019b\u026f"
        + "\u0272\u019e\u0275oo\u01a3\u01a3\u01a5\u01a5\u0280\u01a8\u01a8\u0283\u01aa\u01ab\u01ad\u01ad"
        + "\u0288uu\u028a\u028b\u01b4\u01b4\u01b6\u01b6\u0292\u01b9\u01b9\u01ba\u01bb\u01bd\u01bd\u01be"
        + "\u01bf\u01c0\u01c1\u01c2\u01c3\0\0\0\0\0\0\0\0\0aaiioouuuuuuuuuu\u01ddaaaa\u00e6\u00e6\u01e5"
        + "\u01e5ggkkoooo\u0292\u0292j\0\0\0gg\u0195\u01bfnnaa\u00e6\u00e6\u00f8\u00f8aaaaeeeeiiiioooorrrru"
        + "uuusstt\u021d\u021dhh\u019e\u0221\u0223\u0223\u0225\u0225aaeeooooooooyy\u0234\u0235\u0236\u0237"
        + "\u0238\u0239\u2c65\u023c\u023c\u019a\u2c66\u023f\u0240\u0242\u0242bu\u028c\u0247\u0247\u0249"
        + "\u0249\u024b\u024brr\u024f\u024f";

    /// <summary>Lowercase, unaccented form of U+0370..U+03FF. NUL marks a letter listed in <see cref="Expansion"/>.</summary>
    public const char GreekFirst = '\u0370', GreekLast = '\u03ff';
    public const string Greek =
        "\u0371\u0371\u0373\u0373\u02b9\u0375\u0377\u0377\u0378\u0379\u037a\u037b\u037c\u037d;\u03f3"
        + "\u0380\u0381\u0382\u0383\u0384\u0385\u03b1\u00b7\u03b5\u03b7\u03b9\u038b\u03bf\u038d\u03c5\u03c9"
        + "\u03b9\u03b1\u03b2\u03b3\u03b4\u03b5\u03b6\u03b7\u03b8\u03b9\u03ba\u03bb\u03bc\u03bd\u03be\u03bf"
        + "\u03c0\u03c1\u03a2\u03c3\u03c4\u03c5\u03c6\u03c7\u03c8\u03c9\u03b9\u03c5\u03b1\u03b5\u03b7\u03b9"
        + "\u03c5\u03b1\u03b2\u03b3\u03b4\u03b5\u03b6\u03b7\u03b8\u03b9\u03ba\u03bb\u03bc\u03bd\u03be\u03bf"
        + "\u03c0\u03c1\u03c3\u03c3\u03c4\u03c5\u03c6\u03c7\u03c8\u03c9\u03b9\u03c5\u03bf\u03c5\u03c9\u03d7"
        + "\u03b2\u03b8\u03c5\u03c5\u03c5\u03c6\u03c0\u03d7\u03d9\u03d9\u03db\u03db\u03dd\u03dd\u03df\u03df"
        + "\u03e1\u03e1\u03e3\u03e3\u03e5\u03e5\u03e7\u03e7\u03e9\u03e9\u03eb\u03eb\u03ed\u03ed\u03ef\u03ef"
        + "\u03ba\u03c1\u03c2\u03f3\u03b8\u03b5\u03f6\u03f8\u03f8\u03c2\u03fb\u03fb\u03fc\u037b\u037c\u037d";

    /// <summary>Lowercase, unaccented form of U+0400..U+04FF. NUL marks a letter listed in <see cref="Expansion"/>.</summary>
    public const char CyrillicFirst = '\u0400', CyrillicLast = '\u04ff';
    public const string Cyrillic =
        "\u0435\u0435\u0452\u0433\u0454\u0455\u0456\u0456\u0458\u0459\u045a\u045b\u043a\u0438\u0443\u045f"
        + "\u0430\u0431\u0432\u0433\u0434\u0435\u0436\u0437\u0438\u0438\u043a\u043b\u043c\u043d\u043e\u043f"
        + "\u0440\u0441\u0442\u0443\u0444\u0445\u0446\u0447\u0448\u0449\u044a\u044b\u044c\u044d\u044e\u044f"
        + "\u0430\u0431\u0432\u0433\u0434\u0435\u0436\u0437\u0438\u0438\u043a\u043b\u043c\u043d\u043e\u043f"
        + "\u0440\u0441\u0442\u0443\u0444\u0445\u0446\u0447\u0448\u0449\u044a\u044b\u044c\u044d\u044e\u044f"
        + "\u0435\u0435\u0452\u0433\u0454\u0455\u0456\u0456\u0458\u0459\u045a\u045b\u043a\u0438\u0443\u045f"
        + "\u0461\u0461\u0463\u0463\u0465\u0465\u0467\u0467\u0469\u0469\u046b\u046b\u046d\u046d\u046f\u046f"
        + "\u0471\u0471\u0473\u0473\u0475\u0475\u0475\u0475\u0479\u0479\u047b\u047b\u047d\u047d\u047f\u047f"
        + "\u0481\u0481\u0482\u0483\u0484\u0485\u0486\u0487\u0488\u0489\u048b\u048b\u048d\u048d\u048f\u048f"
        + "\u0491\u0491\u0493\u0493\u0495\u0495\u0497\u0497\u0499\u0499\u049b\u049b\u049d\u049d\u049f\u049f"
        + "\u04a1\u04a1\u04a3\u04a3\u04a5\u04a5\u04a7\u04a7\u04a9\u04a9\u04ab\u04ab\u04ad\u04ad\u04af\u04af"
        + "\u04b1\u04b1\u04b3\u04b3\u04b5\u04b5\u04b7\u04b7\u04b9\u04b9\u04bb\u04bb\u04bd\u04bd\u04bf\u04bf"
        + "\u04cf\u0436\u0436\u04c4\u04c4\u04c6\u04c6\u04c8\u04c8\u04ca\u04ca\u04cc\u04cc\u04ce\u04ce\u04cf"
        + "\u0430\u0430\u0430\u0430\u04d5\u04d5\u0435\u0435\u04d9\u04d9\u04d9\u04d9\u0436\u0436\u0437\u0437"
        + "\u04e1\u04e1\u0438\u0438\u0438\u0438\u043e\u043e\u04e9\u04e9\u04e9\u04e9\u044d\u044d\u0443\u0443"
        + "\u0443\u0443\u0443\u0443\u0447\u0447\u04f7\u04f7\u044b\u044b\u04fb\u04fb\u04fd\u04fd\u04ff\u04ff";

    /// <summary>Lowercase, unaccented form of U+1E00..U+1EFF. NUL marks a letter listed in <see cref="Expansion"/>.</summary>
    public const char LatinAdditionalFirst = '\u1e00', LatinAdditionalLast = '\u1eff';
    public const string LatinAdditional =
        "aabbbbbbccddddddddddeeeeeeeeeeffgghhhhhhhhhhiiiikkkkkkllllllllmmmmmmnnnnnnnnoooooooopppprrrrrrrr"
        + "ssssssssssttttttttuuuuuuuuuuvvvvwwwwwwwwwwxxxxyyzzzzzzhtwy\u1e9as\u1e9c\u1e9d\0\u1e9faaaaaaaaaaa"
        + "aaaaaaaaaaaaaeeeeeeeeeeeeeeeeiiiioooooooooooooooooooooooouuuuuuuuuuuuuuyyyyyyyy\u1efb\u1efb"
        + "\u1efd\u1efd\u1eff\u1eff";

    /// <summary>Letters that fold to more than one character.</summary>
    public static string? Expansion(char c) => c switch
    {
        '\u00c6' => "ae",
        '\u00de' => "th",
        '\u00df' => "ss",
        '\u00e6' => "ae",
        '\u00fe' => "th",
        '\u0132' => "ij",
        '\u0133' => "ij",
        '\u0152' => "oe",
        '\u0153' => "oe",
        '\u01c4' => "dz",
        '\u01c5' => "dz",
        '\u01c6' => "dz",
        '\u01c7' => "lj",
        '\u01c8' => "lj",
        '\u01c9' => "lj",
        '\u01ca' => "nj",
        '\u01cb' => "nj",
        '\u01cc' => "nj",
        '\u01f1' => "dz",
        '\u01f2' => "dz",
        '\u01f3' => "dz",
        '\u1e9e' => "ss",
        _ => null,
    };
}
