using System.Globalization;
using System.Text;
using SkiaSharp;

// Generates src/Fermata/Styles/Icons.axaml, and a preview sheet when given a PNG path.
//
//   dotnet run --project tools/icons [PREVIEW.png]

string root = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../.."));
var icons = Designs.All();

var output = new StringBuilder();
output.AppendLine("""<ResourceDictionary xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">""");
output.AppendLine("  <!-- Fermata's icons on a 24×24 grid, generated by tools/icons. -->");
foreach (var icon in icons)
    output.AppendLine($"""  <StreamGeometry x:Key="Icon.{icon.Name}">{icon.PathData()}</StreamGeometry>""");
output.AppendLine("</ResourceDictionary>");
File.WriteAllText(Path.Combine(root, "src/Fermata/Styles/Icons.axaml"), output.ToString());
Console.WriteLine($"Wrote {icons.Count} icons.");

if (args is [var preview])
{
    Preview.Draw(icons, preview);
    Console.WriteLine($"Wrote {preview}.");
}

/// <summary>An icon built from strokes and filled shapes.</summary>
internal sealed class Icon(string name)
{
    private const float Stroke = 2;
    private readonly SKPath strokes = new();
    private readonly SKPath fills = new();

    public string Name { get; } = name;

    public Icon Line(float x1, float y1, float x2, float y2)
    {
        strokes.MoveTo(x1, y1);
        strokes.LineTo(x2, y2);
        return this;
    }

    public Icon Lines(params float[] points)
    {
        strokes.MoveTo(points[0], points[1]);
        for (int i = 2; i < points.Length; i += 2)
            strokes.LineTo(points[i], points[i + 1]);
        return this;
    }

    public Icon Circle(float cx, float cy, float r)
    {
        strokes.AddCircle(cx, cy, r);
        return this;
    }

    public Icon Dot(float cx, float cy, float r)
    {
        fills.AddCircle(cx, cy, r);
        return this;
    }

    /// <summary>A stroked arc, with angles in degrees clockwise from the positive x axis.</summary>
    public Icon Arc(float cx, float cy, float r, float start, float sweep)
    {
        strokes.ArcTo(new SKRect(cx - r, cy - r, cx + r, cy + r), start, sweep, true);
        return this;
    }

    public Icon Path(string svg)
    {
        strokes.AddPath(SKPath.ParseSvgPathData(svg));
        return this;
    }

    public Icon FillPath(string svg)
    {
        fills.AddPath(SKPath.ParseSvgPathData(svg));
        return this;
    }

    /// <summary>A filled shape whose corners are rounded by half the stroke width.</summary>
    public Icon Solid(string svg)
    {
        var shape = SKPath.ParseSvgPathData(svg);
        fills.AddPath(shape);
        strokes.AddPath(shape);
        return this;
    }

    public Icon Box(float left, float top, float right, float bottom, float radius)
    {
        fills.AddRoundRect(new SKRect(left, top, right, bottom), radius, radius);
        return this;
    }

    /// <summary>The icon as one outline.</summary>
    public SKPath Outline()
    {
        using var paint = new SKPaint { Style = SKPaintStyle.Stroke, StrokeWidth = Stroke, StrokeCap = SKStrokeCap.Round, StrokeJoin = SKStrokeJoin.Round };
        var result = new SKPath();
        using var stroked = new SKPath();
        paint.GetFillPath(strokes, stroked);
        foreach (var part in new[] { stroked, fills })
        {
            using var piece = new SKPath(part) { FillType = SKPathFillType.Winding };
            using var simplified = piece.Simplify() ?? new SKPath(piece);
            using var merged = result.Op(simplified, SKPathOp.Union) ?? new SKPath(result);
            result.Dispose();
            result = new SKPath(merged);
        }
        return result;
    }

    /// <summary>The outline as path data with its fill rule, and with circular conics written as arcs.</summary>
    public string PathData()
    {
        using var outline = Outline();
        var data = new StringBuilder(outline.FillType is SKPathFillType.EvenOdd or SKPathFillType.InverseEvenOdd ? "F0 " : "F1 ");
        using var iterator = outline.CreateRawIterator();
        var points = new SKPoint[4];
        SKPathVerb verb;
        while ((verb = iterator.Next(points)) != SKPathVerb.Done)
        {
            switch (verb)
            {
                case SKPathVerb.Move:
                    Append(data, "M", points[0]);
                    break;
                case SKPathVerb.Line:
                    Append(data, "L", points[1]);
                    break;
                case SKPathVerb.Quad:
                    Append(data, "Q", points[1], points[2]);
                    break;
                case SKPathVerb.Cubic:
                    Append(data, "C", points[1], points[2], points[3]);
                    break;
                case SKPathVerb.Conic:
                    AppendConic(data, points[0], points[1], points[2], iterator.ConicWeight());
                    break;
                case SKPathVerb.Close:
                    data.Append('Z');
                    break;
            }
        }
        return data.ToString();
    }

    /// <summary>Writes a conic that is a circular arc as an arc command, and any other conic as quadratics.</summary>
    private static void AppendConic(StringBuilder data, SKPoint start, SKPoint control, SKPoint end, float weight)
    {
        float chord = SKPoint.Distance(start, end);
        float toControl = SKPoint.Distance(start, control), fromControl = SKPoint.Distance(control, end);
        if (weight is > 0 and < 1 && Math.Abs(toControl - fromControl) < 0.01f && chord > 0.001f)
        {
            float radius = chord / (2 * MathF.Sqrt(1 - weight * weight));
            float turn = (control.X - start.X) * (end.Y - control.Y) - (control.Y - start.Y) * (end.X - control.X);
            data.Append('A').Append(Number(radius)).Append(' ').Append(Number(radius)).Append(" 0 0 ")
                .Append(turn > 0 ? '1' : '0').Append(' ').Append(Number(end.X)).Append(' ').Append(Number(end.Y));
            return;
        }
        var quads = SKPath.ConvertConicToQuads(start, control, end, weight, 2);
        for (int i = 1; i + 1 < quads.Length; i += 2)
            Append(data, "Q", quads[i], quads[i + 1]);
    }

    private static void Append(StringBuilder data, string command, params SKPoint[] points)
    {
        data.Append(command);
        for (int i = 0; i < points.Length; i++)
            data.Append(i == 0 ? "" : " ").Append(Number(points[i].X)).Append(' ').Append(Number(points[i].Y));
    }

    private static string Number(float value) =>
        Math.Round(value, 2).ToString("0.##", CultureInfo.InvariantCulture);
}

/// <summary>A sheet showing every icon at the sizes the app uses.</summary>
internal static class Preview
{
    public static void Draw(IReadOnlyList<Icon> icons, string path)
    {
        const int columns = 8, cell = 150;
        int rows = (icons.Count + columns - 1) / columns;
        using var surface = SKSurface.Create(new SKImageInfo(columns * cell, rows * cell));
        var canvas = surface.Canvas;
        canvas.Clear(new SKColor(0x0D, 0x0D, 0x10));
        using var paint = new SKPaint { Color = new SKColor(0xF3, 0xF3, 0xF5), IsAntialias = true };
        using var label = new SKPaint { Color = new SKColor(0x8A, 0x8A, 0x96), IsAntialias = true };
        using var font = new SKFont(SKTypeface.Default, 13);
        for (int i = 0; i < icons.Count; i++)
        {
            float x = i % columns * cell, y = i / columns * cell;
            string pathData = icons[i].PathData();
            using var outline = SKPath.ParseSvgPathData(pathData[3..]);
            outline.FillType = pathData.StartsWith("F0") ? SKPathFillType.EvenOdd : SKPathFillType.Winding;
            foreach (var (size, dx, dy) in new[] { (72f, 12f, 16f), (24f, 100f, 16f), (20f, 102f, 50f), (32f, 96f, 80f) })
            {
                canvas.Save();
                canvas.Translate(x + dx, y + dy);
                canvas.Scale(size / 24);
                canvas.DrawPath(outline, paint);
                canvas.Restore();
            }
            canvas.DrawText(icons[i].Name, x + 12, y + 128, SKTextAlign.Left, font, label);
        }
        using var image = surface.Snapshot();
        using var data = image.Encode(SKEncodedImageFormat.Png, 100);
        using var file = File.Create(path);
        data.SaveTo(file);
    }
}
