<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAotCompatible>false</IsAotCompatible>
    <RootNamespace>Fermata.Ui</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" Version="12.1.3" />
    <PackageReference Include="Avalonia.Skia" Version="12.1.3" />
    <PackageReference Include="Avalonia.HarfBuzz" Version="12.1.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Fermata/Fermata.csproj" />
  </ItemGroup>
</Project>
