#!/usr/bin/env python3
"""Generate src/Fermata.Core/Text/FoldingTable.g.cs.

Search and sort keys fold case and diacritics ("Sigur Rós" -> "sigur ros").
Fermata runs with invariant globalization, where String.Normalize cannot
decompose text, so the decompositions are precomputed here from Python's
Unicode database and embedded as lookup tables.
"""
import unicodedata
from pathlib import Path

RANGES = [
    (0x00C0, 0x024F, 'Latin'),        # Latin-1 Supplement letters, Latin Extended-A and -B
    (0x0370, 0x03FF, 'Greek'),
    (0x0400, 0x04FF, 'Cyrillic'),
    (0x1E00, 0x1EFF, 'LatinAdditional'),
]

# Letters without a canonical decomposition that readers still expect to match
# their unaccented base letter.
SINGLE = {
    'ø': 'o', 'đ': 'd', 'ħ': 'h', 'ł': 'l', 'ŧ': 't', 'ı': 'i', 'ð': 'd', 'ƒ': 'f',
    'ŋ': 'n', 'ĸ': 'k', 'ſ': 's', 'ς': 'σ', 'ƀ': 'b', 'ɨ': 'i', 'ʉ': 'u', 'ɍ': 'r',
}
MULTI = {'ß': 'ss', 'ẞ': 'ss', 'æ': 'ae', 'œ': 'oe', 'þ': 'th', 'ĳ': 'ij'}


def fold(ch):
    lower = ch.lower() if len(ch.lower()) == 1 else ch
    if lower in MULTI:
        return MULTI[lower]
    if lower in SINGLE:
        return SINGLE[lower]
    decomposed = unicodedata.normalize('NFKD', lower)
    base = ''.join(c for c in decomposed if not unicodedata.combining(c)).lower()
    if not base.strip():
        return lower
    if len(base) > 1:
        return base if base.isascii() and base.isalpha() else lower
    return base


def token(c):
    if c == '\0':
        return '\\0'
    if ord(c) > 0x7E or c in '"\\':
        return '\\u%04x' % ord(c)
    return c


def main():
    root = Path(__file__).resolve().parent.parent
    target = root / 'src/Fermata.Core/Text/FoldingTable.g.cs'
    out = [
        '// <auto-generated>',
        '// Generated by tools/generate-folding.py from the Unicode database. Do not edit.',
        '// </auto-generated>',
        '',
        '#nullable enable',
        '',
        'namespace Fermata.Text;',
        '',
        'internal static class FoldingTable',
        '{',
    ]
    expansions = {}
    for start, end, name in RANGES:
        tokens = []
        for cp in range(start, end + 1):
            folded = fold(chr(cp))
            if len(folded) == 1:
                tokens.append(token(folded))
            else:
                expansions[cp] = folded
                tokens.append(token('\0'))
        out.append(f'    /// <summary>Lowercase, unaccented form of U+{start:04X}..U+{end:04X}. NUL marks a letter listed in <see cref="Expansion"/>.</summary>')
        out.append(f'    public const char {name}First = \'\\u{start:04x}\', {name}Last = \'\\u{end:04x}\';')
        out.append(f'    public const string {name} =')
        lines, current = [], ''
        for t in tokens:
            if len(current) + len(t) > 96:
                lines.append(current)
                current = ''
            current += t
        lines.append(current)
        out.append('        ' + '\n        + '.join(f'"{line}"' for line in lines) + ';')
        out.append('')
    out.append('    /// <summary>Letters that fold to more than one character.</summary>')
    out.append('    public static string? Expansion(char c) => c switch')
    out.append('    {')
    for cp, text in sorted(expansions.items()):
        out.append(f"        '\\u{cp:04x}' => \"{text}\",")
    out.append('        _ => null,')
    out.append('    };')
    out.append('}')
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text('\n'.join(out) + '\n')
    print(f'wrote {target.relative_to(root)} ({len(expansions)} expansions)')


if __name__ == '__main__':
    main()
